---
title: DCDW
timezone: America/New_York
collections:
  aiga-members:
    title: AIGA Members
    output: true
  events:
    title: Events
    output: true
  posts:
    title: Posts
    output: true
  sponsors:
    title: Sponsors
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: events
  values:
    layout: singles/event
    event-bg-image:
    event-date:
    event-location:
    is-featured:
    is-even:
- scope:
    path: ''
    type: sponsors
  values:
    layout: sponsor
    sponsor-image:
    is-2nd-row:
ionicons: http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css
logo-file: "/uploads/dcdw-logo.svg"
contact-email: dcdw@aigadc.org
copyright: "© AIGA DC | 2016 All Rights Reserved."
exclude:
- package.json
- gulpfile.js
- node_modules
- README.md
- Gemfile
- Gemfile.lock
- DesignInsperation.txt
- ".jekyll-metadata"
- ".sass-cache"
sass:
  sass_dir: _sass
  style: compressed
