---
title: DCDW
timezone: America/New_York
collections:
  aiga-members:
    title: AIGA Members
    output: true
  events:
    title: Events
    output: true
  posts:
    title: Posts
    output: true
  sponsors:
    title: Sponsors
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: events
  values:
    layout: singles/event
    event-bg-image: 
    event-date: 
    event-venue-directions: 
    event-venue-name: 
    is-featured-on-home-page: 
    is-even-on-home-page: 
    is-even-on-events-page: 
- scope:
    path: ''
    type: sponsors
  values:
    sponsor-image: 
    is-even-on-home-page: 
    is-1st-tier: 
    1st-tier-header-text: 
    1st-tier-sub-header-text: 
    1st-tier-cta-link: 
    1st-tier-cta-text: 
    is-2nd-tier: 
    2nd-tier-header-text: 
    2nd-tier-sub-header-text: 
    2nd-tier-cta-link: 
    2nd-tier-cta-text: 
    is-3rd-tier: 
    3rd-tier-header-text: 
    3rd-tier-sub-header-text: 
    3rd-tier-cta-link: 
    3rd-tier-cta-text: 
ionicons: http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css
logo-file: "/uploads/dcdw-logo.svg"
contact-email: dcdw@aigadc.org
copyright: "© AIGA DC | 2016 All Rights Reserved."
exclude:
- package.json
- gulpfile.js
- node_modules
- README.md
- Gemfile
- Gemfile.lock
- DesignInsperation.txt
- ".jekyll-metadata"
- ".sass-cache"
sass:
  sass_dir: _sass
  style: compressed
