---
title: DCDW
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  aiga-members:
    title: aiga-members
    output: true
  events:
    title: events
    output: true
  sponsors:
    title: sponsors-row-1
    output: false
    test: test
  sponsors-row-2:
    title: sponsors-row-2
    output: true
defaults:
- scope:
    path: ''
    type: events
  values:
    layout: event
logo-file: "/uploads/dcdw-logo.svg"
exclude:
- package.json
- gulpfile.js
- node_modules
- README.md
- Gemfile
- Gemfile.lock
- DesignInsperation.txt
- ".jekyll-metadata"
- ".sass-cache"
sass:
  sass_dir: _sass
  style: compressed
