---
title: DC Design Week 2019
collections:
    events-dcdw:
        title: Events - DCDW
        output: true
        permalink: "/events/:title/"
    posts:
        title: Posts
        output: true
    uploads:
        title: Uploads
        output: true
defaults:
    - scope:
          path: ""
      values:
          image: "/uploads/og-image.jpg"
          description: "DC Design Week is a celebration of creatives, thinkers, and makers in the DC metro area. Its a week packed with amazing speakers, events, and meetups. Join us!"
    - scope:
          path: ""
          type: "posts"
      values:
          description:
          status:
              is-coming-soon:
              coming-soon-message:
              is-sold-out:
              sold-out-message:
              is-featured-on-events:
              is-featured-on-home:
              featured-event-message:
          event:
              date:
              image:
              image-alt:
              start-time:
              end-time:
              has-external-url: false
              external-url:
              has-speakers:
          tickets:
              has-member-button:
              member-button-url:
              member-button-label:
              member-button-is-disabled:
              has-non-member-button:
              non-member-button-url:
              non-member-button-label:
              non-member-button-is-disabled:
          venue:
              is-tbd:
              name:
              address:
              directions:
          speakers:
              - name:
                title:
                bio:
                website-label:
                website-url:
          filter-date:
              is-day-1:
              is-day-2:
              is-day-3:
              is-day-4:
              is-day-5:
              is-day-6:
              is-day-7:
              is-day-8:
          filter-time:
              is-morning:
              is-daytime:
              is-evening: markdown
              is-screening:
              is-party:
              is-family-friendly:
              is-creative-lunch:
              is-wellness:
              is-workshop:
          filter-location:
              is-dc:
              is-md:
              is-va:
          layout: events-single
# Event List Filter
filter-date:
    - filter: .day-1
      class: day-1
      text-1: Fri
      text-2: Sept
      text-3: 20
      has-occurred: false
    - filter: .day-2
      class: day-2
      text-1: Sat
      text-2: Sept
      text-3: 21
      has-occurred: false
    - filter: .day-3
      class: day-3
      text-1: Sun
      text-2: Sept
      text-3: 22
      has-occurred: false
    - filter: .day-4
      class: day-4
      text-1: Mon
      text-2: Sept
      text-3: 23
      has-occurred: false
    - filter: .day-5
      class: day-5
      text-1: Tue
      text-2: Sept
      text-3: 24
      has-occurred: false
    - filter: .day-6
      class: day-6
      text-1: Wed
      text-2: Sept
      text-3: 25
      has-occurred: false
    - filter: .day-7
      class: day-7
      text-1: Thu
      text-2: Sept
      text-3: 26
      has-occurred: false
    - filter: .day-8
      class: day-8
      text-1: Fri
      text-2: Sept
      text-3: 27
      has-occurred: false
filter-time-of-day:
    - filter: .morning
      class: morning
      text-1: Morning
    - filter: .daytime
      class: daytime
      text-1: Daytime
    - filter: .evening
      class: evening
      text-1: Evening
filter-event-type:
    - filter: .creative-lunch
      class: creative-lunch
      text-1: Creative Lunch
    - filter: .family-friendly
      class: family-friendly
      text-1: Family Friendly
    - filter: .party
      class: party
      text-1: Party
    - filter: .screening
      class: screening
      text-1: Screening
    - filter: .talk
      class: talk
      text-1: Talk
    - filter: .wellness
      class: wellness
      text-1: Wellness
    - filter: .workshop
      class: workshop
      text-1: Workshop
filter-location:
    - filter: .dc
      class: dc
      text-1: DC
    - filter: .md
      class: md
      text-1: MD
    - filter: .va
      class: va
      text-1: VA
filter-sold-out:
    - filter: .sold-out
      class: sold-out
      text-1: Sold Out
filter-status:
    - filter: .featured
      class: featured
      text-1: Show Featured
# Presenting Sponsors
2020-presenting-sponsors:
    - title:
      image:
      image-alt:
      website:
# Contributing Sponsors
2020-contributing-sponsors:
    - title:
      image:
      image-alt:
      website:
# DC Design Week Team
2020-team:
    - image:
      image-alt:
      name:
      role:
      linkedin-url:
      linkedin-label:
      instagram-url:
      instagram-label:
# Global Navigation
navigation-placeholder:
    - url: "https://2016.dcdesignweek.org"
      label: 2016
    - url: "https://2017.dcdesignweek.org"
      label: 2017
    - url: "https://2018.dcdesignweek.org"
      label: 2018
    - url: "https://2019.dcdesignweek.org"
      label: 2019
# Global Subscribe
subscribe:
    body: Stay up to date on everything we have planned to celebrate the DC design community. Follow us on social and sign up below for updates from DCDW and AIGA DC.
# Global Volunteer
volunteer:
    header: Made with <span class="made-in-dc-heart"><i class="fas fa-heart"></i></span> in DC
    body: Built by 100% volunteer power, we're constantly working to make this site better for you. If you see something, say something.
    github: https://github.com/AIGAdc/dcdesignweek.org
ignore-everything-below: <-- IGNORE EVERYTHING BELOW -->
timezone: America/New_York
encoding: utf-8
lang: en-US
theme-color: "#c396ff"
asseturl: "/assets/"
baseurl: ""
url: https://dcdesignweek.org
uploadurl: "/uploads/"
repository: AIGAdc/dcdesignweek.org
email: designweek@dc.aiga.org
google-analytics: UA-84499644-1
facebook:
    publisher: https://www.facebook.com/aigaDC/
twitter:
    username: aigadc
footer:
    links:
        - title: Twitter
          url: https://www.twitter.com/dcdesignweek
          icon: <i class="fab fa-twitter-square"></i>
        - title: Instagram
          url: https://www.instagram.com/dcdesignweek/
          icon: <i class="fab fa-instagram"></i>
        - title: Facebook
          url: https://www.facebook.com/dcdesignweek/
          icon: <i class="fab fa-facebook-square"></i>
    contact: designweek@dc.aiga.org
    copyright: "&copy; AIGA DC | 2020 All Rights Reserved."
exclude:
    - package.json
    - package-lock.json
    - node_modules
    - README.md
    - Gemfile
    - Gemfile.lock
    - ".jekyll-metadata"
    - ".sass-cache"
    - ".ruby-version"
    - _config (copy).yml
markdown: kramdown
kramdown:
    input: GFM
plugins:
    - jekyll-seo-tag
sass:
    sass_dir: "/assets/styles/"
    style: compressed
