---
title: DCDW
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  aiga-members:
    title: aiga-members
    output: true
  events:
    title: events
    output: true
  sponsors:
    title: sponsors
    output: false
defaults:
- scope:
    path: ''
    type: events
  values:
    layout: event
    event-bg-image: 
    is-featured: 
    is-even: 
    event-date: 
    event-location: 
- scope:
    path: ''
    type: sponsors
  values:
    layout: sponsor
    sponsor-image: 
    is-2nd-row: 
logo-file: "/uploads/dcdw-logo.svg"
exclude:
- package.json
- gulpfile.js
- node_modules
- README.md
- Gemfile
- Gemfile.lock
- DesignInsperation.txt
- ".jekyll-metadata"
- ".sass-cache"
sass:
  sass_dir: _sass
  style: compressed
