---
# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Jekyll settings
# 4. Collections
# 5. Jekyll collections settings
# 6. Site settings

# 1. Files excluded from Jekyll builds
exclude:
- package.json
- gulpfile.js
- node_modules
- README.md
- Gemfile
- Gemfile.lock
- DesignInsperation.txt
- ".jekyll-metadata"
- ".sass-cache"

# 2. Installed Gems
plugins:
- jekyll-seo-tag

# 3. Jekyll settings
sass:
  sass_dir: _sass
  style: compressed
timezone: America/New_York # Timezone for blog posts and alike

# 4. Collections
collections:
  posts:
    title: Posts
    output: true
  events:
    title: Events
    output: true
  sponsors:
    title: Sponsors
    output: false
  uploads:
    title: Uploads
    output: true

# 5. Jekyll collections settings
defaults:
- scope:
    path: ''
    type: events
  values:
    seo:
      description: 
      og-image: "/uploads/dcdw_eventPlaceholder.jpg"
    event-details:
      video-embed: 
      date: Displays the date of the event.
      venue-name: Displays the name of the venue.
      venue-directions: Provide a link to google maps to help navigate attendees.
      venue-address: Displays the address of the venues.
      start-time: Displays the start time of the event.
      end-time: Displays the end time of the event.
    event-buttons:
      left-button-link: Provide a link for non-members
      left-button-text: Provide text for button on left
      right-button-link: Provide a link for members
      right-button-text: Provide text for button on right
    speakers:
      headshot-image: Displays the speakers portait.
      link: Provide a link to the speakers website.
      name: Displays the speakers name.
      title: Displays the speakers professional title
      bio-text: Displays the speakers bio.
    single-event-conditionals: 
    is-sold-out: 
    is-featured-on-home-page: 
    is-featured-on-events-page: 
    is-half-feature: 
    is-kickoff-friday: 
    is-sunday: 
    is-monday: 
    is-tuesday: 
    is-wednesday: 
    is-thursday: 
    is-friday: 
    is-saturday: 
    layout: singles/event
- scope:
    path: ''
    type: sponsors
  values:
    sponsor-image: 
    sponsor-url: 
    is-featured-on-home-page: 
    is-featured-on-shops-galleries-page: 
    is-even-on-home-page: 
    is-first-tier: 
    is-second-tier: 
    is-third-tier: 

# 6. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-US # Set the site language
title: "DC Design Week 2018" # Site name or title, also used in jekyll-seo-tag
logo: "/uploads/dcdw-logo.svg" # Site logo, also used in jekyll-seo-tag
description: "DC Design Week is a celebration of creatives, thinkers, and makers in
  the DC metro area. Its a week packed with amazing speakers, events, and meetups.
  Join us!" # Site description and default description, also used in jekyll-seo-tag
og-image: "/uploads/OG_featuredimage-live.jpg" # Site open graph image, also used in jekyll-seo-tag
twitter:
  username: aigadc
facebook:
  publisher: https://www.facebook.com/aigaDC/
url: "https://dcdesignweek.org" # Site url, also used in jekyll-seo-tag
baseurl: ""
repository: AIGAdc/DCDW
email: "designweek@dc.aiga.org"
google-analytics: "<script> \n(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\n
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');\n\n
  \ ga('create', 'UA-84499644-1', 'auto');\n  ga('send', 'pageview');\n</script>"
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference
copyright: "© AIGA DC | 2018  All Rights Reserved."
past-editions: false