---
title: DC Design Week 2019
collections:
  events-dcdw:
    title: Events - DCDW
    output: true
    permalink: "/events/:title/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
  - scope:
      path: ""
    values:
      image: "/uploads/og-image.jpg"
      description: "DC Design Week is a celebration of creatives, thinkers, and makers in the DC metro area. Its a week packed with amazing speakers, events, and meetups. Join us!"
  - scope:
      path: ""
      type: "posts"
    values:
      description:
      status:
        is-coming-soon:
        coming-soon-message:
        is-sold-out:
        sold-out-message:
        is-featured-on-events:
        is-featured-on-home:
        featured-event-message:
      event:
        date:
        image:
        image-alt:
        start-time:
        end-time:
        has-external-url: false
        external-url:
        has-speakers:
      tickets:
        has-member-button:
        member-button-url:
        member-button-label:
        member-button-is-disabled:
        has-non-member-button:
        non-member-button-url:
        non-member-button-label:
        non-member-button-is-disabled:
      venue:
        is-tbd:
        name:
        address:
        directions:
      speakers:
        - name:
          title:
          bio:
          website-label:
          website-url:
      filter-date:
        is-day-1:
        is-day-2:
        is-day-3:
        is-day-4:
        is-day-5:
        is-day-6:
        is-day-7:
        is-day-8:
      filter-time:
        is-morning:
        is-daytime:
        is-evening:
      filter-type:
        is-talk:
        is-screening:
        is-party:
        is-family-friendly:
        is-creative-lunch:
        is-wellness:
        is-workshop:
      filter-location:
        is-dc:
        is-md:
        is-va:
      layout: events-single
2020-presenting-sponsors:
  - title:
    image:
    image-alt:
    website:
2020-contributing-sponsors:
  - title:
    image:
    image-alt:
    website:
2020-team:
  - image:
    image-alt:
    name:
    role:
    linkedin-url:
    linkedin-label:
    instagram-url:
    instagram-label:
2019-featured-events:
  - title: "Shaloin Jazz & Globe Posters: Opening Party"
    image:
    url:
    border-color:
  - title: "Event 2"
    image:
    url:
    border-color:
  - title: "Workshop: The Space Type Continuum"
    image:
    url:
    border-color:
ignore-everything-below: ignore everything below
timezone: America/New_York
encoding: utf-8
lang: en-US
asseturl: "/assets/"
baseurl:
url: https://dcdesignweek.or
uploadurl: "/uploads/"
repository: AIGAdc/dcdesignweek.org
google-analytics: UA-84499644-1
email: designweek@dc.aiga.org
facebook:
  publisher: https://www.facebook.com/aigaDC/
social:
  links:
    - title: Twitter
      url: https://twitter.com/dcdesignweek
      icon: <i class="fab fa-twitter-square"></i>
    - title: Instagram
      url: https://www.instagram.com/dcdesignweek/
      icon: <i class="fab fa-instagram"></i>
    - title: Facebook
      url: https://www.facebook.com/dcdesignweek/
      icon: <i class="fab fa-facebook-square"></i>
  contact: designweek@dc.aiga.org
  copyright: "&copy; AIGA DC | 2020 All Rights Reserved."
twitter:
  username: aigadc
exclude:
  - package.json
  - package-lock.json
  - node_modules
  - README.md
  - Gemfile
  - Gemfile.lock
  - ".jekyll-metadata"
  - ".sass-cache"
  - ".ruby-version"
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-seo-tag
sass:
  sass_dir: "/assets/styles/"
  style: compressed
