---
title: DC Design Week 2018
timezone: America/New_York
collections:
  events:
    title: Events
    output: true
  posts:
    title: Posts
    output: true
  sponsors:
    title: Sponsors
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: events
  values:
    seo:
      description: 
      og-image: "/uploads/dcdw_eventPlaceholder.jpg"
    event-details:
      video-embed: 
      date: Displays the date of the event.
      venue-name: Displays the name of the venue.
      venue-directions: Provide a link to google maps to help navigate attendees.
      venue-address: Displays the address of the venues.
      start-time: Displays the start time of the event.
      end-time: Displays the end time of the event.
    event-buttons:
      left-button-link: Provide a link for non-members
      left-button-text: Provide text for button on left
      right-button-link: Provide a link for members
      right-button-text: Provide text for button on right
    speakers:
      headshot-image: Displays the speakers portait.
      link: Provide a link to the speakers website.
      name: Displays the speakers name.
      title: Displays the speakers professional title
      bio-text: Displays the speakers bio.
    single-event-conditionals: 
    is-sold-out: 
    is-featured-on-home-page: 
    is-featured-on-events-page: 
    is-half-feature: 
    is-kickoff-friday: 
    is-sunday: 
    is-monday: 
    is-tuesday: 
    is-wednesday: 
    is-thursday: 
    is-friday: 
    is-saturday: 
    layout: singles/event
- scope:
    path: ''
    type: sponsors
  values:
    sponsor-image: 
    sponsor-url: 
    is-featured-on-home-page: 
    is-featured-on-shops-galleries-page: 
    is-even-on-home-page: 
    is-first-tier: 
    is-second-tier: 
    is-third-tier: 
exclude:
- package.json
- gulpfile.js
- node_modules
- README.md
- Gemfile
- Gemfile.lock
- DesignInsperation.txt
- ".jekyll-metadata"
- ".sass-cache"
plugins:
- jekyll-seo-tag
sass:
  sass_dir: _sass
  style: compressed
encoding: utf-8
lang: en-US
logo: "/uploads/dcdw-logo.svg"
description: DC Design Week is a celebration of creatives, thinkers, and makers in
  the DC metro area. Its a week packed with amazing speakers, events, and meetups.
  Join us!
og-image: "/uploads/2018-OG-featuredimage.jpg"
twitter:
  username: aigadc
facebook:
  publisher: https://www.facebook.com/aigaDC/
url: https://dcdesignweek.org
baseurl: 
repository: AIGAdc/DCDW
email: designweek@dc.aiga.org
google-analytics: "<script> \n(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\n
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');\n\n
  \ ga('create', 'UA-84499644-1', 'auto');\n  ga('send', 'pageview');\n</script>"
css_inline: true
copyright: "© AIGA DC | 2018  All Rights Reserved."
past-editions: false
