---
title: DC Design Week 2020
timezone: America/New_York
collections:
  events:
    title: Events
    output: true
    permalink: "/events/:title/"
  events-self-guided:
    title: Events - Self Guided
    output: true
    permalink: "/events/self-guided/:title/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    styled-title: 
    image: "/uploads/og-image.jpg"
    description: DC Design Week is a celebration of creatives, thinkers, and makers
      in the DC metro area. Its a week packed with amazing speakers, events, and meetups.
      Join us!
- scope:
    path: ''
    type: events-self-guided
  values:
    header: "DC Design Week: Maker
      Directory"
    body: We’re all about celebrating the DMV’s creative voices — so what better way
      to do that than showcasing their work? We may not be able to do our IRL Pop-Up
      Shop this year, but we’ve got the next best thing. Check out our virtual directory
      for all your fall shopping needs.
    button-url: ''
    button-label: Posters
- scope:
    path: ''
    type: events
  values:
    event-date: 
    start-time: 
    end-time: 
    image: 
    image-alt: 
    description: 
    status:
      is-featured-on-home: 
      featured-home-message: Featured
      is-featured-on-events: 
      featured-event-message: Featured
      is-sold-out: 
      sold-out-message: Sold Out! Sold Out! Sold Out!
      is-limited-supply: 
      limited-supply-message: Limited Tickets
      has-occurred: 
      occurred-message: 
    tickets:
      has-member-button: 
      member-button-url: 
      member-button-label: 
      has-non-member-button: 
      non-member-button-url: 
      non-member-button-label: 
    venue:
      name: 
      info: 
      additional-header: 
      additional-info: 
    has-speakers: 
    speakers:
    - name: 
      pronouns: 
      title: 
      bio: 
      website-label: 
      website-url: 
    has-accessibility-notes: 
    accessibility-notes:
    - note: |-
        All DCDW events will have real-time CART (live captioning) services. If you need any additional accommodations, please contact us before 9/14 by, through the provided Google Form, or by phone. We honor your privacy and no personally identifying information (e.g. your name) is required to request an accommodation.
        * Request an accommodation through this [Google Form](https://forms.gle/gAQviAo5cTwWYGWV6)
        * [Email us](mailto:accessibility@dc.aiga.org) at accessibility@dc.aiga.org.
        * Call our Accessibility Lead, Josh Kim, by phone at 571-302-1504



        You can learn more about how we’re making DC Design Week an accessible experience by visiting our page on [accessibility](/accessibility/).
    filter-date:
      is-day-1: 
      is-day-2: 
      is-day-3: 
      is-day-4: 
      is-day-5: 
      is-day-6: 
      is-day-7: 
      is-day-8: 
    filter-time:
      is-morning: 
      is-daytime: 
      is-evening: 
    filter-type:
      is-creative-breakfast: 
      is-family-friendly: 
      is-keynote: 
      is-partner-events: 
      is-party: 
      is-workshop: 
      is-talk-panel: 
    filter-focus:
      is-fun: 
      is-deia: 
      is-motion: 
      is-skill-building: 
      is-ui-ux: 
    layout: events-landing
about-dcdw:
  header: "About DC Design Week"
  text: |-
    Built by 100% volunteer power, DC Design Week is an annual celebration of this community, hosted by AIGA DC. AIGA Member On-Sale begins 9/5 at 10:00am and the General Public On-Sale begins 9/10 at 10:00am. 100% of the proceeds from DCDW events go toward future AIGA DC programming and the [Design Continuum Fund (DCF) ](https://www.givecontinuum.org/)  scholarship fund. We believe in fostering the next generation of designers through helping local design-minded and underrepresented students as they pursue their education.

    Interested in becoming a member? To gain early access to our most exclusive events and year-long discounts, [sign up to become a member today](https://my.aiga.org/)!
  accessibility-header: Accessibility
  accessibility-text: 'If you need any accommodations to fully access the event, please
    get in touch with us by *Monday, September 16, 2019* at: [designweek@dc.aiga.org](mailto:dcdesignweek@dc.aiga.org).'
  code-of-conduct-header: Code of Conduct
  code-of-conduct-text: All AIGA DC events adhere to our [Code of Conduct](https://dc.aiga.org/events/code-of-conduct/).
  questions-header: Questions?
  questions-text: 'If you have any questions, feel free to reach out to us at: [designweek@dc.aiga.org](mailto:dcdesignweek@dc.aiga.org).'
committee:
  - image: ""
    image-alt: Committee Member Image
    name: Committee Member Name
    role: Committee Member Role
    website-url-1: 
    website-label-1: <i class="fab fa-instagram-square"></i> Instagram
    website-aria-label-1: Committee Member Instagram
    website-url-2: 
    website-label-2: <i class="fab fa-linkedin"></i> LinkedIn
    website-aria-label-2: Committee Member LinkedIn
events-filter:
  day:
  - filter: ".day-1"
    class: day-1
    text-1: Fri
    text-3: 18
    has-occurred: true
  - filter: ".day-2"
    class: day-2
    text-1: Sat
    text-3: 19
    has-occurred: true
  - filter: ".day-3"
    class: day-3
    text-1: Sun
    text-3: 20
    has-occurred: true
  - filter: ".day-4"
    class: day-4
    text-1: Mon
    text-3: 21
    has-occurred: true
  - filter: ".day-5"
    class: day-5
    text-1: Tue
    text-3: 22
    has-occurred: true
  - filter: ".day-6"
    class: day-6
    text-1: Wed
    text-3: 23
    has-occurred: true
  - filter: ".day-7"
    class: day-7
    text-1: Thu
    text-3: 24
    has-occurred: true
  - filter: ".day-8"
    class: day-8
    text-1: Fri
    text-3: 25
    has-occurred: true
  time:
  - filter: ".morning"
    class: morning
    text-1: Morning
  - filter: ".daytime"
    class: daytime
    text-1: Daytime
  - filter: ".evening"
    class: evening
    text-1: Evening
  type:
  - filter: ".creative-breakfast"
    class: creative-breakfast
    text-1: Creative Breakfast
  - filter: ".family-friendly"
    class: family-friendly
    text-1: Family Friendly
  - filter: ".party"
    class: party
    text-1: Party
  - filter: ".keynote"
    class: keynote
    text-1: Keynote
  - filter: ".talk-panel"
    class: talk-panel
    text-1: Talk/Panel
  - filter: ".partner-events"
    class: partner-events
    text-1: Partner Events
  - filter: ".workshop"
    class: workshop
    text-1: Workshop
  focus:
  - filter: ".fun"
    class: fun
    text-1: Fun
  - filter: ".deia"
    class: deia
    text-1: Diversity, Equity, Inclusion, and Accessibility
  - filter: ".motion"
    class: motion
    text-1: Motion Track, by Duke and Duck
  - filter: ".skill-building"
    class: skill-building
    text-1: Skillbuilding
  - filter: ".ui-ux"
    class: ui-ux
    text-1: UI/UX
  sold-out:
  - filter: ".sold-out"
    class: sold-out
    text-1: Sold Out
  status:
  - filter: ".featured"
    class: featured
    text-1: Show Featured
faqs:
  header: "FAQ and Answers"
  body: "We recently held an information session to answer your questions directly. Below are some of the responses from the session:"
  button-url: "/faqs/"
  button-label: "Learn More"
makers:
  header: "DC Design Week: Maker
    Directory"
  body: "We’re all about celebrating the DMV’s creative voices — so what better way
    to do that than showcasing their work? We may not be able to do our IRL Pop-Up
    Shop this year, but we’ve got the next best thing. Check out our virtual directory
    for all your fall shopping needs."
  button-url: "/maker/directory"
  button-label: "Explore Local Artists"
navigation-offseason:
- url: https://2016.dcdesignweek.org
  label: 2016
- url: https://2017.dcdesignweek.org
  label: 2017
- url: https://2018.dcdesignweek.org
  label: 2018
- url: https://2019.dcdesignweek.org
  label: 2019
- url: https://2020.dcdesignweek.org
  label: 2020
navigation-production:
- url: "/events/"
  label: Events
  aria-label: Events Page
- url: "/events/self-guided"
  label: Self Guided
  aria-label: Events - Self Guided Page
- url: "/maker/posters"
  label: Posters
  aria-label: Posters Page
- url: "/maker/directory"
  label: Maker Directory
  aria-label: Maker Directory Page
- url: "/about/"
  label: About
  aria-label: About Page
- url: "/faqs/"
  label: FAQs
  aria-label: FAQs Page
partner:
  header: "Partner with Us"
  body: "DC Design Week is 100% volunteer-run, in concert with a consortium of local associations, meetup groups, and small businesses. We’re looking for sponsors who can help ensure every event is as accessible and inclusive as possible. If you’re interested in partnering with DC Design Week this year, reach out to us here:"
  button-url: mailto:designweek@dc.aiga.org
  button-label: "Become a Partner"
past-editions:
  header: "Past DCDW Years"
  body:
  editions:
  - title: DCDW 2020
    image: "https://www.pcgamesn.com/wp-content/uploads/2019/02/Overwatch-Baptiste-Abilities.jpg"
    url: https://2020.dcdesignweek.org
    aria-label: 2020 DC Design Week Website
  - title: DCDW 2019
    image: "https://www.pcgamesn.com/wp-content/uploads/2019/02/Overwatch-Baptiste-Abilities.jpg"
    url: https://2019.dcdesignweek.org
    aria-label: 2019 DC Design Week Website
  - title: DCDW 2018
    image: "https://www.pcgamesn.com/wp-content/uploads/2019/02/Overwatch-Baptiste-Abilities.jpg"
    url: https://2018.dcdesignweek.org
    aria-label: 2018 DC Design Week Website
  - title: DCDW 2017
    image: "https://www.pcgamesn.com/wp-content/uploads/2019/02/Overwatch-Baptiste-Abilities.jpg"
    url: https://2017.dcdesignweek.org
    aria-label: 2017 DC Design Week Website
  - title: DCDW 2016
    image: "https://www.pcgamesn.com/wp-content/uploads/2019/02/Overwatch-Baptiste-Abilities.jpg"
    url: https://2016.dcdesignweek.org
    aria-label: 2016 DC Design Week Website
posters:
  header: "Limited Edition Posters"
  body: Looking for even more amazing artwork from local artists? We’re delighted
    to also be featuring five limited-edition DCDW posters, created by five up-and-coming
    artists, and available to purchase through [Cherry Blossom Creative <i class="fas
    fa-external-link-square-alt"></i>](https://cherryblossomcreative.com/){:target="_blank"
    rel="noopener nofollow"}. See them all, learn about the artists, and get yours
    today!
  button-url: "/maker/posters"
  button-label: "See All Posters"
proposals:
  header: "New This Year: Hyperlocal"
  body: "We’re excited to announce that this year we’re shifting our focus to feature virtual events curated and hosted by our community — so … you!


  Have no fear, some of your favorite annual events will still be on the calendar (including inspiring keynotes, fun parties, and more!) But this year, because bringing the creative community together is more important than ever, we want to pass the mic to you. While larger events like the kick-off party and keynotes will continue to be planned by the DCDW committee, the goal for the community-curated model is to provide value through partnership by supporting the community in planning their own events for DCDW.


  <strong>Want to submit a proposal?</strong>"
  button-url: mailto:designweek@dc.aiga.org
  button-label: "Submit a Proposal"
self-guided:
  header: "Lorem Ipsum"
  body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac augue id
    lorem eleifend imperdiet in vitae orci. Cras molestie at nisi non porttitor."
  button-url: "/events/self-guided/"
  button-label: "See Self-Guided Events"
sponsors:
  header: "Sponsors and Partners"
  tier-one-header: "Presenting sponsors"
  tier-two-header: "Contributing Sponsors"
  tier-three-header: "Supporting Sponsors"
  body: "DC Design Week wouldn’t be the same without you. <strong>Thank you</strong>
    for your support."
  image-1: ""
  image-1-alt:
  sponsor-tier-one:
  - title: Sponsor Title
    image:
    image-alt: Logo Alt
    website: https://dcdesignweek.org
    aria-label: Website Aria Label
  sponsor-tier-two:
  - title: Sponsor Title
    image:
    image-alt: Logo Alt
    website: https://dcdesignweek.org
    aria-label: Website Aria Label
  sponsor-tier-three:
  - title: Sponsor Title
    image:
    image-alt: Logo Alt
    website: https://dcdesignweek.org
    aria-label: Website Aria Label
subscribe:
  header: "Subscribe for updates"
  body: "Stay up to date on everything we have planned to celebrate the DC design community. Follow us on Instagram, Twitter, LinkedIn, and and sign up below for updates from DCDW and AIGA DC."
  image-1: "/uploads/bubble-black-large-02.png"
  image-1-alt: Floating amorphous bubbles
volunteer:
  header: Made with <span class="made-in-dc-heart"><svg
    xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M462.3 62.6C407.5
    15.9 326 24.3 275.7 76.2L256 96.5l-19.7-20.3C186.1 24.3 104.5 15.9 49.7 62.6c-62.8
    53.6-66.1 149.8-9.9 207.9l193.5 199.8c12.5 12.9 32.8 12.9 45.3 0l193.5-199.8c56.3-58.1
    53-154.3-9.8-207.9z" fill="#ec1001"/></svg> in DC
  unbranded-header: Made with heart in DC
  body: "DC Design Week runs on 100% volunteer power. We’re always working to make
    this site better for you. If you see something, <strong>say something</strong>."
  github: https://github.com/AIGAdc/dcdesignweek.org
  image-1: ""
  image-1-alt: 
ignore-everything-below: "<-- IGNORE EVERYTHING BELOW -->"
encoding: utf-8
lang: en-US
theme-color: "#000000"
asseturl: "/assets/"
baseurl: 
url: https://dcdesignweek.org
email: designweek@dc.aiga.org
google-analytics: UA-84499644-1
facebook:
  publisher: https://www.facebook.com/aigaDC/
twitter:
  username: aigadc
footer:
  links:
  - title: Twitter
    url: https://www.twitter.com/dcdesignweek
    icon: <i class="fab fa-twitter-square"></i>
    aria-label: DC Design Week Twitter Page
  - title: Instagram
    url: https://www.instagram.com/dcdesignweek/
    icon: <i class="fab fa-instagram-square"></i>
    aria-label: DC Design Week Instagram Page
  - title: Facebook
    url: https://www.facebook.com/dcdesignweek/
    icon: <i class="fab fa-facebook-square"></i>
    aria-label: DC Design Week Facebook Page
  - title: Github
    url: https://github.com/AIGAdc/dcdesignweek.org
    icon: <i class="fab fa-github-square"></i>
    aria-label: DC Design Week Github Repository
  contact: designweek@dc.aiga.org
  copyright: "&copy; AIGA DC | 2021 All Rights Reserved."
exclude:
- package.json
- package-lock.json
- node_modules
- README.md
- Gemfile
- Gemfile.lock
- ".jekyll-metadata"
- ".sass-cache"
- ".ruby-version"
- ".jekyll-cache"
include:
- _redirects
markdown: kramdown
kramdown:
  input: GFM
plugins:
- jekyll-seo-tag
sass:
  sass_dir: "/assets/styles/"
  style: compressed
destination: "./build/"
