---
title: DCDW
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  aiga-members:
    title: aiga-members
    output: true
  events:
    title: events
    output: true
  sponsors:
    title: sponsors
    output: true
    test: test
exclude:
- package.json
- gulpfile.js
- node_modules
- README.md
- Gemfile
- Gemfile.lock
- DesignInsperation.txt
- ".jekyll-metadata"
- ".sass-cache"
sass:
  sass_dir: _sass
  style: compressed
