---
title: Dcdw
timezone: UTC

collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

exclude: [ package.json, gulpfile.js, node_modules, README.md, Gemfile, Gemfile.lock, DesignInsperation.txt ]

sass:
  sass_dir: _sass
  style: compressed
